# Generated by Django 4.0.3 on 2023-05-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_answer_author_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hide_author',
            field=models.BooleanField(default=False),
        ),
    ]
