# Generated by Django 4.0.3 on 2023-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_question_hide_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hide_author',
            field=models.BooleanField(default=False),
        ),
    ]
