# Generated by Django 4.0.3 on 2023-06-13 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0009_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
