# Generated by Django 4.0.3 on 2023-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_question_voter_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='free',
            name='subject',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
