# Generated by Django 4.0.3 on 2023-09-25 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_savetip_saveshop_savefree'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tip')),
                ('text', models.TextField(blank=True, null=True)),
                ('tip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.tip')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('text', models.TextField(blank=True, null=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.shopping')),
            ],
        ),
        migrations.CreateModel(
            name='QImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question')),
                ('text', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.question')),
            ],
        ),
        migrations.CreateModel(
            name='FreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='free')),
                ('text', models.TextField(blank=True, null=True)),
                ('free', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.free')),
            ],
        ),
    ]
