# Generated by Django 4.0.3 on 2023-09-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_note_image_noteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='note')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.note')),
            ],
        ),
    ]
