# Generated by Django 4.0.3 on 2023-09-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteimage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
