# Generated by Django 4.0.3 on 2023-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_noteimage_text_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
